# Generated by Django 5.0.6 on 2026-04-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_avatar_pendingregistration_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
