# Generated by Django 5.0.6 on 2026-05-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_avatar_profile_cover_photo_report_block_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='block',
            name='accounts_bl_blocker_746a2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='accounts_re_status_02566d_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='accounts_re_reporte_04daed_idx',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='resolved_at',
            new_name='reviewed_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='target_object_id',
            new_name='target_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='target_content_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('user', 'User')], default='post', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or Bullying'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('nsfw', 'Inappropriate Content'), ('violence', 'Violence or Threats'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker'], name='accounts_bl_blocker_8f03c2_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_type', 'target_id'], name='accounts_re_target__a61117_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='accounts_re_reporte_8da0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='accounts_re_status_859365_idx'),
        ),
    ]
