# Generated by Django 5.0.6 on 2026-04-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned_message',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_in', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
